# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - imageName: gcr.io/istio-next/emailservice
    workspace: src/emailservice
  - imageName: gcr.io/istio-next/productcatalogservice
    workspace: src/productcatalogservice
  - imageName: gcr.io/istio-next/recommendationservice
    workspace: src/recommendationservice
  - imageName: gcr.io/istio-next/shippingservice
    workspace: src/shippingservice
  - imageName: gcr.io/istio-next/checkoutservice
    workspace: src/checkoutservice
  - imageName: gcr.io/istio-next/paymentservice
    workspace: src/paymentservice
  - imageName: gcr.io/istio-next/currencyservice
    workspace: src/currencyservice
  - imageName: gcr.io/istio-next/cartservice
    workspace: src/cartservice
  - imageName: gcr.io/istio-next/frontend
    workspace: src/frontend
  - imageName: gcr.io/istio-next/loadgenerator
    workspace: src/loadgenerator
deploy:
  kubectl:
    manifests:
    - ./kubernetes-manifests/**.yaml
