apiVersion: v2
name: bso-helm
description: A Helm chart for Kubernetes 
# TODO add a proper description

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

dependencies:
  - name: ingress-nginx
    version: ^4.10.1
    repository: https://kubernetes.github.io/ingress-nginx
  - name: opentelemetry-kube-stack
    version: ^0.0.6
  - name: opentelemetry-collector
    version: ^0.93.1
    repository:  https://open-telemetry.github.io/opentelemetry-helm-charts
  - name: influxdb2
    version: ^2.1.2
    repository: https://helm.influxdata.com/
  - name: grafana
    version: ^8.0.0
    repository: https://grafana.github.io/helm-charts
  - name: tempo
    version: ^1.9.0
    repository: https://grafana.github.io/helm-charts
  - name: prometheus
    version: ^25.21.0
    repository: https://prometheus-community.github.io/helm-charts