apiVersion: v1
kind: Secret
metadata:
  name: "email"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "email") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $emailUser :=  (.Values.grafana.email.user | b64enc ) | default (get $secretData "user") }}
  user: {{ $emailUser | quote }}
  {{- $emailPass := (.Values.grafana.email.password | b64enc ) | default (get $secretData "password") }}
  password: {{ $emailPass | quote }}