apiVersion: v1
kind: Secret
metadata:
  name: "grafana"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "grafana") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $grafanaSecret := (get $secretData "password") | default (randAlphaNum 32 | b64enc) }}
  password: {{ $grafanaSecret | quote }}
  username: {{ "admin" | b64enc | quote }}