apiVersion: v1
kind: Secret
metadata:
  name: "influxdb-auth"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "influxdb-auth") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $tokenSecret := (get $secretData "admin-token") | default (randAlphaNum 96 | b64enc | b64enc) }}
  admin-token: {{ $tokenSecret | quote }}
  {{- $passwordSecret := (get $secretData "admin-password") | default (randAlphaNum 32 | b64enc) }}
  admin-password: {{ $passwordSecret | quote }}