apiVersion: v1
kind: Secret
metadata:
  name: "token-secret"
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "token-secret") | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $tokenSecret := (get $secretData "token-secret") | default (randAlphaNum 64 | b64enc) }}
  token: {{ $tokenSecret | quote }}